name: clientcallsaction
on:
  workflow_dispatch:

jobs:
  clientcallsaction:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Test'
        run: |
          touch test.txt
          ls -ltr 

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_iduses

      - name: 'Call action'
        uses: tvdvoorde/actionrepo/.github/actions/dosomething@main
        with:
          comment: "my comment"
